theme = "jba"

[editor]
line-number = "relative"
auto-pairs = true
auto-save = true

[editor.gutters.line-numbers]
min-width = 1

# [editor.cursor-shape]
# insert = "bar"
# normal = "block"
# select = "underline"

[keys.normal."space"]
o = "file_picker_in_current_buffer_directory"

[keys.insert]
"C-f" = "move_char_right"
"C-b" = "move_char_left" 
